language: elixir
elixir:
  - 1.3.4
  - 1.4.0
  - 1.9.4
otp_release:
  - 18.3
  - 19.2
  - 22.0
after_script:
  - mix deps.get --only docs
  - MIX_ENV=dev mix inch.report
notifications:
  recipients:
    - tallak@tveide.net
